---

- hosts: ROUTERCISCO:SWITCHCISCO
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configurar DNS e NTP
      ios_config:
        lines:
          - ip name-server 8.8.8.4
          - clock timezone BRA -3 0
          - ntp server a.st1.ntp.br
          - service password-encryption

- hosts: SWITCHCISCO
  gather_facts: false
  connection: network_cli

  tasks:
    - name: L2 Interface
      cisco.ios.ios_l2_interfaces:
        config:
        - name: Ethernet0/2
          mode: trunk
          trunk:
            encapsulation: dot1q
            native_vlan: 1
            allowed_vlans: 20-25
        state: merged

    - name: VLAN 10
      cisco.ios.ios_vlans:
        config:
        - name: vlan_10_data
          vlan_id: 10
          state: active
          shutdown: disabled
        state: merged

    - name: STP e Save Config
      ios_config:
        lines:
          - spanning-tree mode rapid-pvst
          - spanning-tree portfast edge default
          - do wr